### ISSUE TITLE
Construct3?

### ISSUE THREAD

**Issue by chrystoffer** [Mimiste/c2-groundfollow-behavior#1]
Any possibility of using this addon in Construct3?

**Comment by loic-martinez-freelance** [comment]
Yes it should work, once converted to C3 addon format
Did you tried this converter ? It's a pretty basic addon, maybe the conversion should work.

https://www.construct.net/fr/forum/construct-3/plugin-sdk-10/plugin-converter-123855

**Comment by chrystoffer** [comment]
I did not try, I never used addons in the construct, this was my first one and I really liked it. I'll try when you're home. thank you.
